<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sf</string>
	</array>
	<key>name</key>
	<string>F2J</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>[ 	]*--.*</string>
			<key>name</key>
			<string>comment.line.f2j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control keywords</string>
			<key>match</key>
			<string>\b(let|rec|and|type|module|end|then|else|if|in|case)\b</string>
			<key>name</key>
			<string>keyword.control.f2j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Seperator</string>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.other.f2j</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.c</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.c</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.f2j</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>\#string_escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>\#string_placeholder</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Storage Type</string>
			<key>match</key>
			<string>\b(Int|String|List|Unit)\b</string>
			<key>name</key>
			<string>storage.type.f2j</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.f2j</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>comment</key>
			<string>Parens</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.parens.f2j</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(let|and)\s+(?!\(\*)((rec\s+)([a-z_][a-zA-Z0-9_']*)\b|([a-z_][a-zA-Z0-9_']*|\([^)]+\))(?=\s)((?=\s*=\s*(?=fun(?:ction)\b))|(?!\s*=)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.function-definition.f2j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.funtion-definition.f2j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f2j</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.f2j</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function Definition</string>
			<key>end</key>
			<string>(?:(:)\s*([^=]+))?(?:(=)|(=)\s*(?=fun(?:ction)\b))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.function.type-constraint.f2j</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.f2j</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.f2j</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.f2j</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.f2j</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>\#variables</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(type)\s+([_A-Za-z][_A-Za-z0-9]*\b)+</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.f2j</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Type definition</string>
			<key>end</key>
			<string>=</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.f2j</string>
	<key>uuid</key>
	<string>571d3901-a922-4ea8-a839-4da85c1b28d0</string>
</dict>
</plist>
